# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Share it freely - but don't take a slice of my pie!"
description: > # this means to ignore newlines until "email:"
   We build business applications quickly  
email: keith@appzco.uk
#blog logo
logo: "https://dummyimage.com/200x200/000/fff.png&text=A"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/blockchain_mini.jpg"

name: 'Keith Garrod'
author: 'Keith Garrod'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://appzco.uk" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@kpgarrod'

#fill in disqus shortname to use disqus
disqus: kpgarrod

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/kpgarrod
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=kpgarrod
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/kpgarrod
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/kpgarrod
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
