# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Share it fairly"
description: > # this means to ignore newlines until "email:"
   but don't take a slice of my pie!   
email: keith@shareitfairly.org
#blog logo
logo: "https://dummyimage.com/200x200/000/fff.png&text=$"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/blockchain_mini.jpg"

name: 'Keith Garrod'
author: 'Keith Garrod'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://shareitfairly.org" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@shareitfairly'

#fill in disqus shortname to use disqus
disqus: kpgarrod

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/shareitfairly
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=shareitfairly
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/shareitfairly
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/kpgarrod
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
